In [1]:
""" External Imports """
import maboss
import pandas as pd
import matplotlib.pyplot as plt
import sys
import numpy as np
sys.path.append("/Users/emilieyu/endotehelial-masboss")

ipylab module is not installed, menus and toolbar are disabled.

In [2]:
from src.config import load_bm_sim_cfg, load_bm_sweep_cfg
from src.paths import *
from boolean_models.scripts import *

In [3]:
sim_cfg = load_bm_sim_cfg()
sweep_cfg = load_bm_sweep_cfg()

MODELS_BND = DATA_DIR / sim_cfg['model']['bnd_v2']
MODELS_CFG = DATA_DIR / sim_cfg['model']['cfg_v4']

In [4]:
""" Setup base model. """
base_model = maboss.load(str(MODELS_BND), str(MODELS_CFG))
base_model.param['max_time'] = 10.0
base_model.param['sample_count'] = 5000

## Recruitment Sweep

In [8]:
joint_sweep_recruitment = run_sweeps(base_model, sweep_cfg, sim_cfg, target_exp="Joint_Recr_Sweep", result_dir=BM_RESULTS_DIR)
joint_sweep_recruitment

>>> DEBUG: Initialising: Joint_Recr_Sweep (3D)
DEBUG: Starting Joint_Recr_Sweep sweep for perturbation: WT
DEBUG: 216 combinations — $DSP_recruitment×$TJP1_recruitment×$JCAD_recruitment
  0/216 done
  100/216 done
  200/216 done
DEBUG: Completed Joint_Recr_Sweep for perturbation: WT
DEBUG: File param_sweep_Joint_Recr_Sweep.csv successfully written to directory: /Users/emilieyu/endotehelial-masboss/results/boolean_models
DEBUG: Combined parameter sweep experiment data saved to /Users/emilieyu/endotehelial-masboss/results/boolean_models

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,p3_name,p3_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.004200,0.004201,0.394807,0.406481,0.003800,$DSP_recruitment,0.0,$TJP1_recruitment,0.0,$JCAD_recruitment,0.0,WT,Joint_Recr_Sweep,3D,0.011674,Normal
9.9000,0.002400,0.285392,0.398707,0.402562,0.002958,$DSP_recruitment,0.0,$TJP1_recruitment,0.0,$JCAD_recruitment,0.2,WT,Joint_Recr_Sweep,3D,0.003855,Normal
9.9000,0.003764,0.454191,0.402209,0.394472,0.002800,$DSP_recruitment,0.0,$TJP1_recruitment,0.0,$JCAD_recruitment,0.4,WT,Joint_Recr_Sweep,3D,-0.007737,Normal
9.9000,0.002400,0.543487,0.399349,0.395211,0.002122,$DSP_recruitment,0.0,$TJP1_recruitment,0.0,$JCAD_recruitment,0.6,WT,Joint_Recr_Sweep,3D,-0.004138,Normal
9.9000,0.005000,0.619245,0.403229,0.410087,0.003576,$DSP_recruitment,0.0,$TJP1_recruitment,0.0,$JCAD_recruitment,0.8,WT,Joint_Recr_Sweep,3D,0.006858,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.9000,0.665174,0.283850,0.559892,0.563358,0.667026,$DSP_recruitment,1.0,$TJP1_recruitment,1.0,$JCAD_recruitment,0.2,WT,Joint_Recr_Sweep,3D,0.003466,Normal
9.9000,0.664702,0.441447,0.587059,0.593669,0.663782,$DSP_recruitment,1.0,$TJP1_recruitment,1.0,$JCAD_recruitment,0.4,WT,Joint_Recr_Sweep,3D,0.006610,Normal
9.9000,0.671722,0.538985,0.614872,0.602716,0.668403,$DSP_recruitment,1.0,$TJP1_recruitment,1.0,$JCAD_recruitment,0.6,WT,Joint_Recr_Sweep,3D,-0.012156,Normal
9.9000,0.671863,0.605706,0.614559,0.637633,0.678286,$DSP_recruitment,1.0,$TJP1_recruitment,1.0,$JCAD_recruitment,0.8,WT,Joint_Recr_Sweep,3D,0.023074,Normal
9.9000,0.667378,0.670080,0.629504,0.638105,0.671004,$DSP_recruitment,1.0,$TJP1_recruitment,1.0,$JCAD_recruitment,1.0,WT,Joint_Recr_Sweep,3D,0.008601,Normal

In [7]:
df = joint_sweep_recruitment.copy()
df[(df['p1_value'] == df['p2_value']) & (df['p2_value'] == df['p3_value'])]

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,p3_name,p3_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.004200,0.004748,0.411337,0.387952,0.003146,$DSP_recruitment,0.0,$TJP1_recruitment,0.0,$JCAD_recruitment,0.0,WT,Joint_Recr_Sweep,3D,-0.023385,Normal
9.9000,0.294406,0.287916,0.475708,0.476860,0.287166,$DSP_recruitment,0.2,$TJP1_recruitment,0.2,$JCAD_recruitment,0.2,WT,Joint_Recr_Sweep,3D,0.001152,Normal
9.9000,0.438328,0.446333,0.528297,0.536986,0.441207,$DSP_recruitment,0.4,$TJP1_recruitment,0.4,$JCAD_recruitment,0.4,WT,Joint_Recr_Sweep,3D,0.008689,Normal
9.9000,0.552422,0.555106,0.582972,0.561368,0.547930,$DSP_recruitment,0.6,$TJP1_recruitment,0.6,$JCAD_recruitment,0.6,WT,Joint_Recr_Sweep,3D,-0.021604,Normal
9.9000,0.615323,0.632100,0.614914,0.610319,0.613910,$DSP_recruitment,0.8,$TJP1_recruitment,0.8,$JCAD_recruitment,0.8,WT,Joint_Recr_Sweep,3D,-0.004595,Normal
9.9000,0.664154,0.669846,0.636443,0.618714,0.653149,$DSP_recruitment,1.0,$TJP1_recruitment,1.0,$JCAD_recruitment,1.0,WT,Joint_Recr_Sweep,3D,-0.017729,Normal

## Run Perturbations and Parameter Sweeps

In [6]:
perb_full_df, ss_df = run_perturbations(base_model, sim_cfg)
ss_df

DEBUG: Running perturbation: WT
DEBUG: Running perturbation: DSP_KO
DEBUG: Running perturbation: TJP1_KO
DEBUG: Running perturbation: JCAD_KO
DEBUG: Running perturbation: DSP_JCAD_DKO
DEBUG: Running perturbation: TJP1_JCAD_DKO
DEBUG: All simulations completed successfully

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
0,9.9,0.000000,0.661295,0.000000,0.378205,0.600772,DSP_JCAD_DKO,0.222567,Normal
1,9.9,0.000000,0.661048,0.662283,0.251231,0.795533,DSP_KO,0.544302,Hyper
2,9.9,0.668700,0.667842,0.000000,0.523592,0.514232,JCAD_KO,-0.009360,Normal
3,9.9,0.670368,0.000000,0.000000,0.613813,0.364588,TJP1_JCAD_DKO,-0.249225,Normal
4,9.9,0.670409,0.000000,0.668916,0.805174,0.263563,TJP1_KO,-0.541611,Failed
5,9.9,0.673050,0.678001,0.666478,0.641849,0.647216,WT,0.005367,Normal

In [7]:
perb_full_df[perb_full_df['perturbation'] == 'DSP_KO']

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
100,0.0,0.0,0.514226,0.501792,0.480802,0.540472,DSP_KO,0.059670,Normal
101,0.1,0.0,0.533480,0.529835,0.439276,0.577077,DSP_KO,0.137801,Normal
102,0.2,0.0,0.548431,0.553320,0.411529,0.598250,DSP_KO,0.186721,Normal
103,0.3,0.0,0.567669,0.573883,0.392933,0.619097,DSP_KO,0.226164,Normal
104,0.4,0.0,0.585875,0.587684,0.377390,0.639372,DSP_KO,0.261982,Hyper
...,...,...,...,...,...,...,...,...,...
195,9.5,0.0,0.665066,0.664002,0.249143,0.798495,DSP_KO,0.549352,Hyper
196,9.6,0.0,0.666688,0.663990,0.248656,0.796984,DSP_KO,0.548328,Hyper
197,9.7,0.0,0.666717,0.665825,0.254614,0.797122,DSP_KO,0.542508,Hyper
198,9.8,0.0,0.665251,0.666997,0.253387,0.798341,DSP_KO,0.544954,Hyper
199,9.9,0.0,0.663825,0.667325,0.247365,0.798756,DSP_KO,0.551391,Hyper

In [4]:
joint_sweep_recruitment = run_sweeps(base_model, sweep_cfg, sim_cfg, target_exp="Joint_Recr_Sweep", result_dir=None)
joint_sweep_recruitment

NameError: name 'base_model' is not defined

In [10]:
sweep_1d = run_sweeps(base_model, sweep_cfg, sim_cfg, target_type='1D')

>>> DEBUG: Initialising: WT_Sweep (1D)
DEBUG: Starting WT_Sweep sweep for perturbation: WT with dict_keys(['$RhoA_amp', '$RhoA_mod', '$RhoA_basal', '$RhoA_antagonistic', '$RhoA_decay', '$RhoC_amp', '$RhoC_mod', '$RhoC_basal', '$RhoC_antagonistic', '$RhoC_decay'])
DEBUG: Completed WT_Sweep sweep for perturbation: WT

>>> DEBUG: Initialising: DSP_Sweep (1D)
DEBUG: Starting DSP_Sweep sweep for perturbation: DSP_KO with ['$RhoC_antagonistic', '$RhoC_mod', '$RhoC_amp', '$RhoC_decay']
DEBUG: Completed DSP_Sweep sweep for perturbation: DSP_KO

>>> DEBUG: Initialising: TJP1_Sweep (1D)
DEBUG: Starting TJP1_Sweep sweep for perturbation: TJP1_KO with ['$RhoA_antagonistic', '$RhoA_mod', '$RhoA_amp', '$RhoA_decay']
DEBUG: Completed TJP1_Sweep sweep for perturbation: TJP1_KO

>>> DEBUG: Initialising: JCAD_Sweep (1D)
DEBUG: Starting JCAD_Sweep sweep for perturbation: JCAD_KO with ['$RhoA_mod', '$RhoC_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed JCAD_Sweep sweep for perturbation: JCAD_KO

>>> DEBUG: Initialising: DSP_JCAD_Sweep (1D)
DEBUG: Starting DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO with ['$RhoC_mod', '$RhoC_basal', '$RhoA_basal']
DEBUG: Completed DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO

>>> DEBUG: Initialising: TJP1_JCAD_Sweep (1D)
DEBUG: Starting TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO with ['$RhoA_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO

>>> DEBUG: Initialising: DSP_TJP1_Sweep (1D)
DEBUG: Starting DSP_TJP1_Sweep sweep for perturbation: DSP_TJP1_DKO with ['$RhoA_basal', '$RhoC_basal']
ERROR: Failed experiment DSP_TJP1_Sweep: 'DSP_TJP1_DKO'
DEBUG: Combined parameter sweep experiment data saved to None

In [15]:
sweep_1d

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.505201,0.506200,0.344931,0.626727,0.488000,$RhoA_amp,0.0,N/A,NaN,WT,WT_Sweep,1D,0.281796,Hyper
9.9000,0.501000,0.492201,0.494898,0.567507,0.499800,$RhoA_amp,2.5,N/A,NaN,WT,WT_Sweep,1D,0.072609,Normal
9.9000,0.497201,0.491400,0.528119,0.563373,0.502201,$RhoA_amp,5.0,N/A,NaN,WT,WT_Sweep,1D,0.035254,Normal
9.9000,0.493600,0.502799,0.541637,0.562828,0.500400,$RhoA_amp,7.5,N/A,NaN,WT,WT_Sweep,1D,0.021191,Normal
9.9000,0.506802,0.495000,0.552135,0.549716,0.494602,$RhoA_amp,10.0,N/A,NaN,WT,WT_Sweep,1D,-0.002419,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.9000,0.496800,NaN,0.555410,0.420602,NaN,$RhoC_basal,0.6,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.134808,Normal
9.9000,0.505800,NaN,0.533125,0.488441,NaN,$RhoC_basal,0.8,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.044684,Normal
9.9000,0.499400,NaN,0.492281,0.544280,NaN,$RhoC_basal,1.0,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.051999,Normal
9.9000,0.503401,NaN,0.468640,0.582252,NaN,$RhoC_basal,1.2,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.113612,Normal
9.9000,0.506400,NaN,0.453891,0.617342,NaN,$RhoC_basal,1.4,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.163451,Normal