In [15]:
""" External Imports """
import maboss
import pandas as pd
import matplotlib.pyplot as plt
import sys
import numpy as np
sys.path.append("/Users/emilieyu/endotehelial-masboss")

In [17]:
from src.config import load_sim_config, load_sweep_config
from src.paths import *
from boolean_models.scripts import *

In [19]:
sim_cfg = load_sim_config()
sweep_cfg = load_sweep_config()

MODELS_BND = DATA_DIR / sim_cfg['model']['bnd']
MODELS_CFG = DATA_DIR / sim_cfg['model']['cfg_v3']

In [20]:
""" Setup base model. """
base_model = maboss.load(str(MODELS_BND), str(MODELS_CFG))
base_model.param['max_time'] = 10.0
base_model.param['sample_count'] = 5000

## Run Perturbations and Parameter Sweeps

In [ ]:
perb_full_df, ss_df = run_perturbations(base_model, sim_cfg, BM_RESULTS_DIR)

DEBUG: Running perturbation: WT
DEBUG: Running perturbation: DSP_KO
DEBUG: Running perturbation: TJP1_KO
DEBUG: Running perturbation: JCAD_KO
DEBUG: Running perturbation: DSP_JCAD_DKO
DEBUG: Running perturbation: TJP1_JCAD_DKO
DEBUG: All simulations completed successfully
DEBUG: File perturbation_timeseries.csv successfully written to directory: /Users/emilieyu/endotehelial-masboss/results/boolean_models
DEBUG: File perturbation_steady_state.csv successfully written to directory: /Users/emilieyu/endotehelial-masboss/results/boolean_models

NameError: name 'perb_df' is not defined

In [23]:
ss_df

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
0,9.9,0.000000,0.508199,0.000000,0.380575,0.573171,DSP_JCAD_DKO,0.192596,Normal
1,9.9,0.000000,0.493400,0.491000,0.359724,0.621070,DSP_KO,0.261346,Hyper
2,9.9,0.494599,0.492200,0.000000,0.491389,0.497129,JCAD_KO,0.005740,Normal
3,9.9,0.508200,0.000000,0.000000,0.556378,0.399463,TJP1_JCAD_DKO,-0.156915,Normal
4,9.9,0.509601,0.000000,0.497600,0.627876,0.352698,TJP1_KO,-0.275178,Failed
5,9.9,0.494401,0.499199,0.500601,0.541583,0.550238,WT,0.008655,Normal

In [24]:
ss_mask = perb_df.groupby('perturbation')['t'].idxmax()
ss_mask

perturbation
DSP_JCAD_DKO     499
DSP_KO           199
JCAD_KO          399
TJP1_JCAD_DKO    599
TJP1_KO          299
WT                99
Name: t, dtype: int64

In [25]:
ss_df = perb_df.loc[ss_mask].reset_index(drop=True)
ss_df

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
0,9.9,0.000000,0.494200,0.000000,0.402969,0.553519,DSP_JCAD_DKO,0.150550,Normal
1,9.9,0.000000,0.500601,0.506002,0.359385,0.623825,DSP_KO,0.264440,Hyper
2,9.9,0.489400,0.507400,0.000000,0.497615,0.499833,JCAD_KO,0.002218,Normal
3,9.9,0.498800,0.000000,0.000000,0.559186,0.391166,TJP1_JCAD_DKO,-0.168020,Normal
4,9.9,0.503000,0.000000,0.501800,0.639055,0.353138,TJP1_KO,-0.285917,Failed
5,9.9,0.493799,0.510999,0.507399,0.553949,0.552547,WT,-0.001402,Normal

In [ ]:
#sweep_results = run_sweeps(base_model, BM_RESULTS_DIR, sweep_cfg, sim_cfg)

In [10]:
sweep_1d = run_sweeps(base_model, sweep_cfg, sim_cfg, target_type='1D')

>>> DEBUG: Initialising: WT_Sweep (1D)
DEBUG: Starting WT_Sweep sweep for perturbation: WT with dict_keys(['$RhoA_amp', '$RhoA_mod', '$RhoA_basal', '$RhoA_antagonistic', '$RhoA_decay', '$RhoC_amp', '$RhoC_mod', '$RhoC_basal', '$RhoC_antagonistic', '$RhoC_decay'])
DEBUG: Completed WT_Sweep sweep for perturbation: WT

>>> DEBUG: Initialising: DSP_Sweep (1D)
DEBUG: Starting DSP_Sweep sweep for perturbation: DSP_KO with ['$RhoC_antagonistic', '$RhoC_mod', '$RhoC_amp', '$RhoC_decay']
DEBUG: Completed DSP_Sweep sweep for perturbation: DSP_KO

>>> DEBUG: Initialising: TJP1_Sweep (1D)
DEBUG: Starting TJP1_Sweep sweep for perturbation: TJP1_KO with ['$RhoA_antagonistic', '$RhoA_mod', '$RhoA_amp', '$RhoA_decay']
DEBUG: Completed TJP1_Sweep sweep for perturbation: TJP1_KO

>>> DEBUG: Initialising: JCAD_Sweep (1D)
DEBUG: Starting JCAD_Sweep sweep for perturbation: JCAD_KO with ['$RhoA_mod', '$RhoC_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed JCAD_Sweep sweep for perturbation: JCAD_KO

>>> DEBUG: Initialising: DSP_JCAD_Sweep (1D)
DEBUG: Starting DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO with ['$RhoC_mod', '$RhoC_basal', '$RhoA_basal']
DEBUG: Completed DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO

>>> DEBUG: Initialising: TJP1_JCAD_Sweep (1D)
DEBUG: Starting TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO with ['$RhoA_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO

>>> DEBUG: Initialising: DSP_TJP1_Sweep (1D)
DEBUG: Starting DSP_TJP1_Sweep sweep for perturbation: DSP_TJP1_DKO with ['$RhoA_basal', '$RhoC_basal']
ERROR: Failed experiment DSP_TJP1_Sweep: 'DSP_TJP1_DKO'
DEBUG: Combined parameter sweep experiment data saved to None

In [15]:
sweep_1d

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.505201,0.506200,0.344931,0.626727,0.488000,$RhoA_amp,0.0,N/A,NaN,WT,WT_Sweep,1D,0.281796,Hyper
9.9000,0.501000,0.492201,0.494898,0.567507,0.499800,$RhoA_amp,2.5,N/A,NaN,WT,WT_Sweep,1D,0.072609,Normal
9.9000,0.497201,0.491400,0.528119,0.563373,0.502201,$RhoA_amp,5.0,N/A,NaN,WT,WT_Sweep,1D,0.035254,Normal
9.9000,0.493600,0.502799,0.541637,0.562828,0.500400,$RhoA_amp,7.5,N/A,NaN,WT,WT_Sweep,1D,0.021191,Normal
9.9000,0.506802,0.495000,0.552135,0.549716,0.494602,$RhoA_amp,10.0,N/A,NaN,WT,WT_Sweep,1D,-0.002419,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.9000,0.496800,NaN,0.555410,0.420602,NaN,$RhoC_basal,0.6,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.134808,Normal
9.9000,0.505800,NaN,0.533125,0.488441,NaN,$RhoC_basal,0.8,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.044684,Normal
9.9000,0.499400,NaN,0.492281,0.544280,NaN,$RhoC_basal,1.0,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.051999,Normal
9.9000,0.503401,NaN,0.468640,0.582252,NaN,$RhoC_basal,1.2,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.113612,Normal
9.9000,0.506400,NaN,0.453891,0.617342,NaN,$RhoC_basal,1.4,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.163451,Normal