In [1]:
""" External Imports """
import maboss
import pandas as pd
import matplotlib.pyplot as plt
import sys
import numpy as np
sys.path.append("/Users/emilieyu/endotehelial-masboss")

ipylab module is not installed, menus and toolbar are disabled.

In [2]:
from src.config import load_sim_config, load_sweep_config
from src.paths import *
from boolean_models.scripts import *

In [3]:
sim_cfg = load_sim_config()
sweep_cfg = load_sweep_config()

MODELS_BND = DATA_DIR / sim_cfg['model']['bnd_v2']
MODELS_CFG = DATA_DIR / sim_cfg['model']['cfg_v4']

In [4]:
""" Setup base model. """
base_model = maboss.load(str(MODELS_BND), str(MODELS_CFG))
base_model.param['max_time'] = 10.0
base_model.param['sample_count'] = 5000

## Run Perturbations and Parameter Sweeps

In [5]:
perb_full_df, ss_df = run_perturbations(base_model, sim_cfg, BM_RESULTS_DIR)

DEBUG: Running perturbation: WT
DEBUG: Running perturbation: DSP_KO
DEBUG: Running perturbation: TJP1_KO
DEBUG: Running perturbation: JCAD_KO
DEBUG: Running perturbation: DSP_JCAD_DKO
DEBUG: Running perturbation: TJP1_JCAD_DKO
DEBUG: All simulations completed successfully
DEBUG: File perturbation_timeseries.csv successfully written to directory: /Users/emilieyu/endotehelial-masboss/results/boolean_models
DEBUG: File perturbation_steady_state.csv successfully written to directory: /Users/emilieyu/endotehelial-masboss/results/boolean_models

In [6]:
perb_full_df[perb_full_df['perturbation'] == 'DSP_KO']

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
100,0.0,0.0,0.520590,0.514356,0.476001,0.524294,DSP_KO,0.048293,Normal
101,0.1,0.0,0.541264,0.536503,0.441700,0.557235,DSP_KO,0.115535,Normal
102,0.2,0.0,0.556815,0.550392,0.412422,0.583963,DSP_KO,0.171541,Normal
103,0.3,0.0,0.573327,0.561691,0.389890,0.607141,DSP_KO,0.217251,Normal
104,0.4,0.0,0.586493,0.574912,0.376699,0.627103,DSP_KO,0.250404,Hyper
...,...,...,...,...,...,...,...,...,...
195,9.5,0.0,0.654058,0.664122,0.248316,0.802030,DSP_KO,0.553714,Hyper
196,9.6,0.0,0.658433,0.660779,0.250947,0.798856,DSP_KO,0.547909,Hyper
197,9.7,0.0,0.659826,0.657380,0.252089,0.796559,DSP_KO,0.544470,Hyper
198,9.8,0.0,0.663607,0.657388,0.256044,0.795091,DSP_KO,0.539047,Hyper
199,9.9,0.0,0.661347,0.657832,0.257688,0.792566,DSP_KO,0.534878,Hyper

In [5]:
sweep_recruitment = run_sweeps(base_model, sweep_cfg, sim_cfg, target_exp="Recruitment_Sweep", result_dir=BM_RESULTS_DIR)
sweep_recruitment

>>> DEBUG: Initialising: Recruitment_Sweep (1D)
DEBUG: Starting Recruitment_Sweep sweep for perturbation: WT with ['$DSP_recruitment', '$TJP1_recruitment', '$JCAD_recruitment']
DEBUG: Completed Recruitment_Sweep sweep for perturbation: WT
DEBUG: File param_sweep_Recruitment_Sweep.csv successfully written to directory: /Users/emilieyu/endotehelial-masboss/results/boolean_models
DEBUG: Combined parameter sweep experiment data saved to /Users/emilieyu/endotehelial-masboss/results/boolean_models

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.004253,0.672796,0.254891,0.799573,0.658068,$DSP_recruitment,0.00,NaN,NaN,WT,Recruitment_Sweep,1D,0.544682,Hyper
9.9000,0.097307,0.665449,0.311121,0.776847,0.668666,$DSP_recruitment,0.05,NaN,NaN,WT,Recruitment_Sweep,1D,0.465726,Hyper
9.9000,0.168571,0.669735,0.351689,0.758400,0.652176,$DSP_recruitment,0.10,NaN,NaN,WT,Recruitment_Sweep,1D,0.406711,Hyper
9.9000,0.228347,0.673717,0.400811,0.733204,0.670572,$DSP_recruitment,0.15,NaN,NaN,WT,Recruitment_Sweep,1D,0.332393,Hyper
9.9000,0.284235,0.663617,0.424944,0.724783,0.661081,$DSP_recruitment,0.20,NaN,NaN,WT,Recruitment_Sweep,1D,0.299839,Hyper
9.9000,0.337507,0.665741,0.456223,0.710882,0.657179,$DSP_recruitment,0.25,NaN,NaN,WT,Recruitment_Sweep,1D,0.254659,Hyper
9.9000,0.363679,0.674995,0.476185,0.713070,0.668123,$DSP_recruitment,0.30,NaN,NaN,WT,Recruitment_Sweep,1D,0.236885,Normal
9.9000,0.415984,0.665235,0.500968,0.696838,0.675474,$DSP_recruitment,0.35,NaN,NaN,WT,Recruitment_Sweep,1D,0.195870,Normal
9.9000,0.449280,0.668620,0.519842,0.686418,0.658094,$DSP_recruitment,0.40,NaN,NaN,WT,Recruitment_Sweep,1D,0.166576,Normal
9.9000,0.465802,0.678368,0.536075,0.684849,0.665027,$DSP_recruitment,0.45,NaN,NaN,WT,Recruitment_Sweep,1D,0.148774,Normal
9.9000,0.486738,0.667051,0.547770,0.678650,0.667861,$DSP_recruitment,0.50,NaN,NaN,WT,Recruitment_Sweep,1D,0.130880,Normal
9.9000,0.523656,0.678603,0.554433,0.697251,0.669316,$DSP_recruitment,0.55,NaN,NaN,WT,Recruitment_Sweep,1D,0.142818,Normal
9.9000,0.545610,0.656123,0.578796,0.658628,0.655422,$DSP_recruitment,0.60,NaN,NaN,WT,Recruitment_Sweep,1D,0.079832,Normal
9.9000,0.556125,0.662207,0.587693,0.650391,0.667738,$DSP_recruitment,0.65,NaN,NaN,WT,Recruitment_Sweep,1D,0.062698,Normal
9.9000,0.568300,0.673509,0.587301,0.664255,0.658157,$DSP_recruitment,0.70,NaN,NaN,WT,Recruitment_Sweep,1D,0.076954,Normal
9.9000,0.602499,0.670804,0.609696,0.649576,0.659784,$DSP_recruitment,0.75,NaN,NaN,WT,Recruitment_Sweep,1D,0.039880,Normal
9.9000,0.600092,0.664906,0.607033,0.652855,0.664106,$DSP_recruitment,0.80,NaN,NaN,WT,Recruitment_Sweep,1D,0.045822,Normal
9.9000,0.637232,0.653452,0.621361,0.643006,0.658239,$DSP_recruitment,0.85,NaN,NaN,WT,Recruitment_Sweep,1D,0.021645,Normal
9.9000,0.642357,0.669097,0.620999,0.656892,0.673285,$DSP_recruitment,0.90,NaN,NaN,WT,Recruitment_Sweep,1D,0.035893,Normal
9.9000,0.645742,0.663693,0.635200,0.635240,0.660327,$DSP_recruitment,0.95,NaN,NaN,WT,Recruitment_Sweep,1D,0.000040,Normal
9.9000,0.675385,0.665603,0.794773,0.258896,0.004358,$TJP1_recruitment,0.00,NaN,NaN,WT,Recruitment_Sweep,1D,-0.535877,Failed
9.9000,0.662223,0.658987,0.768936,0.315509,0.100294,$TJP1_recruitment,0.05,NaN,NaN,WT,Recruitment_Sweep,1D,-0.453427,Failed
9.9000,0.663783,0.665699,0.759302,0.350600,0.164110,$TJP1_recruitment,0.10,NaN,NaN,WT,Recruitment_Sweep,1D,-0.408702,Failed
9.9000,0.661282,0.674299,0.735154,0.405257,0.234496,$TJP1_recruitment,0.15,NaN,NaN,WT,Recruitment_Sweep,1D,-0.329897,Failed
9.9000,0.667933,0.660555,0.732869,0.434713,0.297390,$TJP1_recruitment,0.20,NaN,NaN,WT,Recruitment_Sweep,1D,-0.298156,Failed
9.9000,0.662255,0.654441,0.722806,0.452561,0.337823,$TJP1_recruitment,0.25,NaN,NaN,WT,Recruitment_Sweep,1D,-0.270245,Failed
9.9000,0.667646,0.673492,0.702383,0.489576,0.380698,$TJP1_recruitment,0.30,NaN,NaN,WT,Recruitment_Sweep,1D,-0.212807,Normal
9.9000,0.659019,0.666116,0.704752,0.491745,0.404862,$TJP1_recruitment,0.35,NaN,NaN,WT,Recruitment_Sweep,1D,-0.213007,Normal
9.9000,0.671211,0.658637,0.688470,0.518512,0.443111,$TJP1_recruitment,0.40,NaN,NaN,WT,Recruitment_Sweep,1D,-0.169958,Normal
9.9000,0.666944,0.663720,0.679360,0.535387,0.465279,$TJP1_recruitment,0.45,NaN,NaN,WT,Recruitment_Sweep,1D,-0.143973,Normal
9.9000,0.668280,0.664690,0.684082,0.544536,0.498519,$TJP1_recruitment,0.50,NaN,NaN,WT,Recruitment_Sweep,1D,-0.139546,Normal
9.9000,0.673899,0.648916,0.672087,0.566956,0.528653,$TJP1_recruitment,0.55,NaN,NaN,WT,Recruitment_Sweep,1D,-0.105131,Normal
9.9000,0.672585,0.667255,0.667174,0.568985,0.529165,$TJP1_recruitment,0.60,NaN,NaN,WT,Recruitment_Sweep,1D,-0.098189,Normal
9.9000,0.659601,0.661467,0.658125,0.598705,0.570470,$TJP1_recruitment,0.65,NaN,NaN,WT,Recruitment_Sweep,1D,-0.059420,Normal
9.9000,0.664841,0.662035,0.666333,0.584447,0.576148,$TJP1_recruitment,0.70,NaN,NaN,WT,Recruitment_Sweep,1D,-0.081886,Normal
9.9000,0.662365,0.671678,0.658700,0.597380,0.600318,$TJP1_recruitment,0.75,NaN,NaN,WT,Recruitment_Sweep,1D,-0.061320,Normal
9.9000,0.661458,0.666539,0.648354,0.622989,0.622063,$TJP1_recruitment,0.80,NaN,NaN,WT,Recruitment_Sweep,1D,-0.025365,Normal
9.9000,0.667940,0.662547,0.648413,0.623974,0.633921,$TJP1_recruitment,0.85,NaN,NaN,WT,Recruitment_Sweep,1D,-0.024439,Normal
9.9000,0.654829,0.672916,0.642387,0.635301,0.649763,$TJP1_recruitment,0.90,NaN,NaN,WT,Recruitment_Sweep,1D,-0.007086,Normal
9.9000,0.660615,0.669769,0.641034,0.643819,0.662725,$TJP1_recruitment,0.95,NaN,NaN,WT,Recruitment_Sweep,1D,0.002785,Normal
9.9000,0.680301,0.003601,0.522554,0.527020,0.676703,$JCAD_recruitment,0.00,NaN,NaN,WT,Recruitment_Sweep,1D,0.004466,Normal
9.9000,0.657527,0.085561,0.530848,0.537324,0.671198,$JCAD_recruitment,0.05,NaN,NaN,WT,Recruitment_Sweep,1D,0.006476,Normal
9.9000,0.665468,0.175141,0.554969,0.549955,0.660390,$JCAD_recruitment,0.10,NaN,NaN,WT,Recruitment_Sweep,1D,-0.005014,Normal
9.9000,0.670625,0.226362,0.572016,0.552470,0.662498,$JCAD_recruitment,0.15,NaN,NaN,WT,Recruitment_Sweep,1D,-0.019546,Normal
9.9000,0.657829,0.287108,0.573301,0.578932,0.675813,$JCAD_recruitment,0.20,NaN,NaN,WT,Recruitment_Sweep,1D,0.005631,Normal
9.9000,0.673904,0.322275,0.577712,0.580259,0.666674,$JCAD_recruitment,0.25,NaN,NaN,WT,Recruitment_Sweep,1D,0.002547,Normal
9.9000,0.654427,0.377094,0.582975,0.590275,0.670691,$JCAD_recruitment,0.30,NaN,NaN,WT,Recruitment_Sweep,1D,0.007300,Normal
9.9000,0.663402,0.414369,0.600624,0.598210,0.670005,$JCAD_recruitment,0.35,NaN,NaN,WT,Recruitment_Sweep,1D,-0.002414,Normal
9.9000,0.678249,0.440027,0.606780,0.600131,0.674593,$JCAD_recruitment,0.40,NaN,NaN,WT,Recruitment_Sweep,1D,-0.006649,Normal
9.9000,0.659243,0.465582,0.604880,0.619485,0.675043,$JCAD_recruitment,0.45,NaN,NaN,WT,Recruitment_Sweep,1D,0.014605,Normal
9.9000,0.663022,0.504017,0.614327,0.610133,0.679068,$JCAD_recruitment,0.50,NaN,NaN,WT,Recruitment_Sweep,1D,-0.004194,Normal
9.9000,0.672448,0.521597,0.616052,0.609675,0.662724,$JCAD_recruitment,0.55,NaN,NaN,WT,Recruitment_Sweep,1D,-0.006377,Normal
9.9000,0.658885,0.548869,0.616868,0.618052,0.661457,$JCAD_recruitment,0.60,NaN,NaN,WT,Recruitment_Sweep,1D,0.001184,Normal
9.9000,0.670962,0.557128,0.616231,0.615101,0.660863,$JCAD_recruitment,0.65,NaN,NaN,WT,Recruitment_Sweep,1D,-0.001130,Normal
9.9000,0.673531,0.578458,0.626670,0.624541,0.667349,$JCAD_recruitment,0.70,NaN,NaN,WT,Recruitment_Sweep,1D,-0.002129,Normal
9.9000,0.652595,0.609162,0.634085,0.627961,0.648243,$JCAD_recruitment,0.75,NaN,NaN,WT,Recruitment_Sweep,1D,-0.006124,Normal
9.9000,0.675557,0.608760,0.634589,0.620384,0.670714,$JCAD_recruitment,0.80,NaN,NaN,WT,Recruitment_Sweep,1D,-0.014205,Normal
9.9000,0.651001,0.625115,0.628682,0.633020,0.658660,$JCAD_recruitment,0.85,NaN,NaN,WT,Recruitment_Sweep,1D,0.004338,Normal
9.9000,0.668853,0.642862,0.635404,0.635453,0.675304,$JCAD_recruitment,0.90,NaN,NaN,WT,Recruitment_Sweep,1D,0.000049,Normal
9.9000,0.664173,0.654748,0.640244,0.645261,0.666765,$JCAD_recruitment,0.95,NaN,NaN,WT,Recruitment_Sweep,1D,0.005017,Normal

In [10]:
sweep_1d = run_sweeps(base_model, sweep_cfg, sim_cfg, target_type='1D')

>>> DEBUG: Initialising: WT_Sweep (1D)
DEBUG: Starting WT_Sweep sweep for perturbation: WT with dict_keys(['$RhoA_amp', '$RhoA_mod', '$RhoA_basal', '$RhoA_antagonistic', '$RhoA_decay', '$RhoC_amp', '$RhoC_mod', '$RhoC_basal', '$RhoC_antagonistic', '$RhoC_decay'])
DEBUG: Completed WT_Sweep sweep for perturbation: WT

>>> DEBUG: Initialising: DSP_Sweep (1D)
DEBUG: Starting DSP_Sweep sweep for perturbation: DSP_KO with ['$RhoC_antagonistic', '$RhoC_mod', '$RhoC_amp', '$RhoC_decay']
DEBUG: Completed DSP_Sweep sweep for perturbation: DSP_KO

>>> DEBUG: Initialising: TJP1_Sweep (1D)
DEBUG: Starting TJP1_Sweep sweep for perturbation: TJP1_KO with ['$RhoA_antagonistic', '$RhoA_mod', '$RhoA_amp', '$RhoA_decay']
DEBUG: Completed TJP1_Sweep sweep for perturbation: TJP1_KO

>>> DEBUG: Initialising: JCAD_Sweep (1D)
DEBUG: Starting JCAD_Sweep sweep for perturbation: JCAD_KO with ['$RhoA_mod', '$RhoC_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed JCAD_Sweep sweep for perturbation: JCAD_KO

>>> DEBUG: Initialising: DSP_JCAD_Sweep (1D)
DEBUG: Starting DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO with ['$RhoC_mod', '$RhoC_basal', '$RhoA_basal']
DEBUG: Completed DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO

>>> DEBUG: Initialising: TJP1_JCAD_Sweep (1D)
DEBUG: Starting TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO with ['$RhoA_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO

>>> DEBUG: Initialising: DSP_TJP1_Sweep (1D)
DEBUG: Starting DSP_TJP1_Sweep sweep for perturbation: DSP_TJP1_DKO with ['$RhoA_basal', '$RhoC_basal']
ERROR: Failed experiment DSP_TJP1_Sweep: 'DSP_TJP1_DKO'
DEBUG: Combined parameter sweep experiment data saved to None

In [15]:
sweep_1d

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.505201,0.506200,0.344931,0.626727,0.488000,$RhoA_amp,0.0,N/A,NaN,WT,WT_Sweep,1D,0.281796,Hyper
9.9000,0.501000,0.492201,0.494898,0.567507,0.499800,$RhoA_amp,2.5,N/A,NaN,WT,WT_Sweep,1D,0.072609,Normal
9.9000,0.497201,0.491400,0.528119,0.563373,0.502201,$RhoA_amp,5.0,N/A,NaN,WT,WT_Sweep,1D,0.035254,Normal
9.9000,0.493600,0.502799,0.541637,0.562828,0.500400,$RhoA_amp,7.5,N/A,NaN,WT,WT_Sweep,1D,0.021191,Normal
9.9000,0.506802,0.495000,0.552135,0.549716,0.494602,$RhoA_amp,10.0,N/A,NaN,WT,WT_Sweep,1D,-0.002419,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.9000,0.496800,NaN,0.555410,0.420602,NaN,$RhoC_basal,0.6,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.134808,Normal
9.9000,0.505800,NaN,0.533125,0.488441,NaN,$RhoC_basal,0.8,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.044684,Normal
9.9000,0.499400,NaN,0.492281,0.544280,NaN,$RhoC_basal,1.0,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.051999,Normal
9.9000,0.503401,NaN,0.468640,0.582252,NaN,$RhoC_basal,1.2,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.113612,Normal
9.9000,0.506400,NaN,0.453891,0.617342,NaN,$RhoC_basal,1.4,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.163451,Normal