In [5]:
import pandas as pd
import sys
import matplotlib.pyplot as plt
import matplotlib.pyplot as mpatches 
sys.path.append("/Users/emilieyu/endotehelial-masboss")

from src.paths import EXP_DIR
EXP_DIR

PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation')

In [8]:
print(EXP_DIR)
print(EXP_DIR.exists())
print(list(EXP_DIR.glob("*")))

/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation
True
[PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoA.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoC_siTJP1.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoA_siJCAD.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoC.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/.DS_Store'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siTJP1.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siCONT_001a.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoC_siDSP.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoC_siJCAD.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoA_siTJP1.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siJCAD_siDSP.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siJCAD.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siJCAD_siTJP1.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siDSP_siTJP1.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/readme.rtf'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siRhoA_siDSP.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siDSP.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siCONT_2.csv'), PosixPath('/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siCONT_001.csv')]

In [10]:
wt_csv = EXP_DIR / "siCONT_001.csv"
dsp_ko_csv = EXP_DIR / "siDSP.csv"
tjp1_ko_csv = EXP_DIR / "siTJP1.csv"

print(dsp_ko_csv)
print(type(dsp_ko_csv))
print(dsp_ko_csv.exists())

/Users/emilieyu/endotehelial-masboss/CSV_Files/Elongation/siDSP.csv
<class 'pathlib.PosixPath'>
True

In [15]:
wt_df = pd.read_csv(wt_csv)
dsp_ko_df = pd.read_csv(dsp_ko_csv)
tjp1_ko_df = pd.read_csv(tjp1_ko_csv)

wt_ar_mean = wt_df['Major/Minor Ratio'].mean()
dsp_ar_mean = dsp_ko_df['Major/Minor Ratio'].mean()
tjp1_ar_mean = tjp1_ko_df['Major/Minor Ratio'].mean()
print(f"WT AR Mean: {wt_ar_mean}")
print(f"DSP KO AR Mean: {dsp_ar_mean}")
print(f"TJP1 KO AR Mean: {tjp1_ar_mean}")
wt_df

WT AR Mean: 5.592069944118363
DSP KO AR Mean: 7.046723423019233
TJP1 KO AR Mean: 3.371328936093925

,Label,Centroid_Y,Centroid_X,Major/Minor Ratio,Major Axis Length,Minor Axis Length,Perimeter,Area,Circularity
0,80,32.497813,1626.787901,4.267978,88.068277,20.634662,209.214249,1372.0,0.393896
1,82,75.774142,1075.353875,4.761166,170.819025,35.877564,393.611219,3148.0,0.255335
2,83,66.620061,857.080685,4.228190,141.461477,33.456749,331.865007,3619.0,0.412929
3,84,157.454990,3192.883105,11.545983,312.915981,27.101718,718.027525,5321.0,0.129694
4,85,111.294788,3237.595789,9.130515,196.401794,21.510483,469.842712,2897.0,0.164912
...,...,...,...,...,...,...,...,...,...
2010,2881,2831.758651,1069.655709,2.729613,92.676802,33.952364,232.107648,2312.0,0.539286
2011,2883,2831.940189,1666.610155,2.849447,95.482207,33.509036,235.078210,2324.0,0.528471
2012,2893,2838.155768,1483.272777,6.268908,215.329577,34.348818,473.379726,5444.0,0.305287
2013,2894,2831.265768,1605.077089,2.326911,79.467875,34.151657,220.059921,1855.0,0.481362
2014,2899,2839.021779,967.781609,2.031663,66.423070,32.693947,179.616270,1653.0,0.643860

In [12]:
wt_df['Major/Minor Ratio'].mean()

np.float64(5.592069944118363)

In [14]:
dsp_ko_df = pd.read_csv(dsp_ko_csv)
dsp_ko_df

,Label,Centroid_Y,Centroid_X,Major/Minor Ratio,Major Axis Length,Minor Axis Length,Perimeter,Area,Circularity
0,82,123.857792,1076.554507,4.402797,266.211929,60.464271,638.239682,8797.0,0.271379
1,83,56.840256,3302.122045,9.391793,145.821353,15.526465,321.025433,1565.0,0.190829
2,84,127.722538,2977.609164,22.692132,412.361478,18.172002,831.904725,5107.0,0.092732
3,85,35.563549,3376.587530,3.227264,71.978474,22.303248,168.267027,1251.0,0.555225
4,86,53.867444,674.304404,4.793355,210.480393,43.910871,560.191955,4632.0,0.185483
...,...,...,...,...,...,...,...,...,...
2401,3473,2831.526728,2306.760756,1.612556,58.868310,36.506205,169.840620,1534.0,0.668270
2402,3475,2835.168308,2477.413276,5.409153,130.893744,24.198567,285.722871,2335.0,0.359424
2403,3480,2840.622439,438.860976,6.223055,135.103498,21.710156,305.965512,2050.0,0.275181
2404,3484,2832.851137,1721.364576,7.154605,116.302059,16.255552,254.876154,1451.0,0.280685
2405,3490,2846.586272,620.176775,8.162010,161.015672,19.727454,338.124892,2127.0,0.233788