In [1]:
import sys
sys.path.append("/Users/emilieyu/endotehelial-masboss")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import copy

from abm.rho_lookup_table import RhoLookupTable
from abm.endothelial_cell import EndothelialCell
from src.config import load_abm_sim_cfg, load_bm_sweep_cfg
from src.paths import BM_RESULTS_DIR

from abm.scripts.run_abm_sim import run_abm_sim, run_abm_sim_single, plot_cell

sim_cfg = load_abm_sim_cfg()
lut = RhoLookupTable(sim_cfg, BM_RESULTS_DIR)
perbs = sim_cfg['perturbations']

>>> DEBUG: Successfully loaded recruitment parameter sweep data.
>>> DEBUG: Successfully built interpolators
LUT ready | rest: RhoA=0.395 RhoC=0.406

In [2]:
ts_df, ss_df, diag_ts_df, diag_ss_df = run_abm_sim(sim_cfg, lut, 3000, plot=False)

>>> INFO: Running abm simulation perturbation: WT (3000 steps).
WT                  5.034    180.0°  0.783  0.349  0.607
>>> INFO: Running abm simulation perturbation: DSP_KO (3000 steps).
DSP_KO              6.399      0.0°  0.921  0.273  0.639
>>> INFO: Running abm simulation perturbation: TJP1_KO (3000 steps).
TJP1_KO             3.959    180.0°  0.668  0.493  0.353
>>> INFO: Running abm simulation perturbation: JCAD_KO (3000 steps).
JCAD_KO             5.058    180.0°  0.848  0.337  0.591
>>> INFO: Running abm simulation perturbation: DSP_JCAD_DKO (3000 steps).
DSP_JCAD_DKO        6.514      0.0°  0.959  0.284  0.621
>>> INFO: Running abm simulation perturbation: TJP1_JCAD_DKO (3000 steps).
TJP1_JCAD_DKO       4.201   -180.0°  0.767  0.461  0.370

In [3]:
ss_df

,perturbation,cell_id,ar,orientation,area_ratio,mean_rhoa,mean_rhoc,a_sf,sf_tension,a_cortex_pole,mean_integrity
0,WT,0,5.034,180.0,0.9876,0.349,0.607,0.783,13.782,2.658,0.634032
1,DSP_KO,0,6.399,0.0,0.8983,0.273,0.639,0.921,19.484,2.049,0.437027
2,TJP1_KO,0,3.959,180.0,1.0068,0.493,0.353,0.668,9.406,3.352,0.376971
3,JCAD_KO,0,5.058,180.0,1.0138,0.337,0.591,0.848,15.528,2.561,0.496688
4,DSP_JCAD_DKO,0,6.514,0.0,0.9204,0.284,0.621,0.959,21.007,2.134,0.322115
5,TJP1_JCAD_DKO,0,4.201,-180.0,0.9646,0.461,0.370,0.767,11.075,3.093,0.203249

In [4]:
diag_ss_df

,perturbation,shear_fn_pole,shear_fn_lat,shear_fn_diff,shear_tangential,cortex_T_pole,cortex_T_lat,a_cortex_pole,a_cortex_lat,sf_tension,sf_node_max,a_sf,area_pressure
0,WT,10.837,0.952,9.885,17.226,6.532,7.811,2.658,2.138,13.782,6.8910,0.0,2.7377
1,DSP_KO,9.753,0.557,9.196,17.356,7.843,8.478,2.049,2.134,19.484,9.7420,0.0,22.4076
2,TJP1_KO,11.854,1.406,10.448,17.058,5.764,7.392,3.352,2.594,9.406,4.7030,0.0,0.0000
3,JCAD_KO,10.763,0.882,9.881,17.238,7.005,7.991,2.561,2.137,15.528,7.7640,0.0,0.0000
4,DSP_JCAD_DKO,9.729,0.530,9.199,17.359,8.558,8.879,2.134,2.134,21.007,10.5035,0.0,17.5478
5,TJP1_JCAD_DKO,11.589,1.278,10.311,17.106,5.589,7.474,3.093,2.591,11.075,5.5375,0.0,7.8119