In [1]:
import sys
sys.path.append("/Users/emilieyu/endotehelial-masboss")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import copy

from abm.rho_lookup_table import RhoLookupTable
from src.config import load_abm_sim_cfg, load_bm_sweep_cfg
from src.paths import BM_RESULTS_DIR

from abm.scripts.run_abm_sim import run_abm_sim, run_abm_sim_single

sim_cfg = load_abm_sim_cfg()
lut = RhoLookupTable(sim_cfg, BM_RESULTS_DIR)
perbs = sim_cfg['perturbations']

>>> DEBUG: Successfully loaded recruitment parameter sweep data.
>>> DEBUG: Successfully built interpolators
LUT ready | rest: RhoA=0.395 RhoC=0.406

In [ ]:
ts_df, ss_df, diag_ts_df, diag_ss_df = run_abm_sim(sim_cfg, lut, 2000)

>>> INFO: Running abm simulation perturbation: WT (5000 steps).
WT                  4.125    180.0°  0.347  0.395  0.612
>>> INFO: Running abm simulation perturbation: DSP_KO (5000 steps).
DSP_KO              5.204    180.0°  0.437  0.258  0.666
>>> INFO: Running abm simulation perturbation: TJP1_KO (5000 steps).

In [3]:
ss_df

,perturbation,cell_id,ar,orientation,area_ratio,mean_rhoa,mean_rhoc,a_sf,sf_tension,cortex_k_pole
0,WT,0,4.125,180.0,1.0259,0.395,0.612,0.347,7.872,2.507
1,DSP_KO,0,5.204,180.0,1.0315,0.258,0.666,0.437,13.655,1.165
2,TJP1_KO,0,3.270,0.0,1.0013,0.575,0.309,0.000,0.000,3.495
3,JCAD_KO,0,4.423,180.0,0.9964,0.364,0.572,0.281,6.677,2.196
4,DSP_JCAD_DKO,0,4.598,0.0,1.0556,0.283,0.620,0.360,9.859,1.417
5,TJP1_JCAD_DKO,0,3.410,0.0,1.0018,0.503,0.346,0.000,0.000,2.890

In [4]:
diag_ss_df

,perturbation,shear_fn_pole,shear_fn_lat,shear_fn_diff,shear_tangential,cortex_T_pole,cortex_T_lat,cortex_k_pole,cortex_k_lat,sf_tension,sf_node_max,sf_squeeze_max,a_sf,fa_force,area_pressure
0,WT,9.096,0.937,8.159,12.768,3.307,4.815,2.507,1.444,7.872,3.9360,4.7231,0.3468,7.580,0.0000
1,DSP_KO,7.758,0.361,7.397,12.975,4.149,5.121,1.165,1.415,13.655,6.8277,8.1932,0.4367,11.088,0.0000
2,TJP1_KO,9.439,1.708,7.731,12.651,3.602,4.968,3.495,2.248,0.000,0.0000,0.0000,0.0000,4.478,0.0000
3,JCAD_KO,8.759,0.895,7.864,12.824,3.234,4.967,2.196,1.452,6.677,3.3386,4.0063,0.2810,7.561,0.8012
4,DSP_JCAD_DKO,8.319,0.560,7.759,12.901,3.703,4.890,1.417,1.416,9.859,4.9295,5.9154,0.3603,9.212,0.0000
5,TJP1_JCAD_DKO,9.208,1.589,7.619,12.704,3.542,4.928,2.890,2.141,0.000,0.0000,0.0000,0.0000,4.738,0.0000